version: '3.8'
services:
  ubuntu:
    image: ubuntu
    command: bash  # Déplacé ici, à la place de la section 'develop'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    develop: {}  # Laissez vide ou configurez correctement si nécessaire
