services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-image
    ports:
      - "5252:5252"
    expose:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-image
    ports:
      - "9000:9000"
    depends_on:
      - back-end
