services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-image
    expose:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-image
    expose:
      - "9000"
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-image
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
